network_identifier:
  blockchain: IoTeX
  network: mainnet
currency:
  symbol: IOTX
  decimals: 18
server:
  port: 8081
  endpoint: 35.200.17.194:14014
  secureEndpoint: false
  rosettaVersion: 1.4.2
