network_identifier:
  blockchain: IoTeX
  network: testnet
currency:
  symbol: IOTX
  decimals: 18
server:
  port: 8080
  endpoint: 34.106.54.109:14014
  secureEndpoint: false
  rosettaVersion: 1.3.5
pacificBlockHeight: 432001
keepGrantReward: true
keepPutPollResult: true